/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

public class App {

    public static void main(String[] args) {

        RomanNumeral converter = new RomanNumeral();

        if(args.length != 2) {
            System.out.println("Wrong number of arguments");
            System.out.println(" Usage: java RomanNumeralApplication action value");
            System.out.println("\taction: encode or decode");
            System.out.println("\tvalue: either a number for encode or a roman numeral string for decode");
            System.exit(-1);
        }

        if("encode".equals(args[0]) ) {
            try {
                Integer value = Integer.valueOf(args[1]);

                System.out.println(converter.encode(value));
            } catch (NumberFormatException e) {
                System.out.println("Cannot create proper number from " + args[1]);
                System.out.println(e.getMessage());
            }
        }
        else if("encode".equals(args[1]) ) {
            try {
                Integer value = Integer.valueOf(args[0]);

                System.out.println(converter.encode(value));
            } catch (NumberFormatException e) {
                System.out.println("Cannot create proper number from " + args[0]);
                System.out.println(e.getMessage());
            }
        }
        else if("decode".equals(args[0]) ) {
            System.out.println(converter.decode(args[1]));
        }
        else if("decode".equals(args[1]) ) {

            System.out.println(converter.decode(args[0]));
        }

    }


}// end App
